version: '3.8'

services:
  app:
    build: .
    container_name: mine-chan-backend
    ports:
      - "8080:8080"
    depends_on:
      - redis
    environment:
      - REDIS_HOST=redis
      - REDIS_PORT=6379
      - PYTHONUNBUFFERED=1
    volumes:
      - .:/app

  redis:
    image: "redis:7.0-alpine"
    container_name: mine-chan-redis
    ports:
      - "6379:6379"
    volumes:
      - redis-data:/data

volumes:
  redis-data:
