/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface CreateGame
 */
export interface CreateGame {
    /**
     * プレイヤー数
     * @type {number}
     * @memberof CreateGame
     */
    numPlayer: number;
    /**
     * 地雷の数
     * @type {number}
     * @memberof CreateGame
     */
    numMines: number;
    /**
     * x軸の長さ
     * @type {number}
     * @memberof CreateGame
     */
    x: number;
    /**
     * y軸の長さ
     * @type {number}
     * @memberof CreateGame
     */
    y: number;
}

/**
 * Check if a given object implements the CreateGame interface.
 */
export function instanceOfCreateGame(value: object): boolean {
    if (!('numPlayer' in value)) return false;
    if (!('numMines' in value)) return false;
    if (!('x' in value)) return false;
    if (!('y' in value)) return false;
    return true;
}

export function CreateGameFromJSON(json: any): CreateGame {
    return CreateGameFromJSONTyped(json, false);
}

export function CreateGameFromJSONTyped(json: any, ignoreDiscriminator: boolean): CreateGame {
    if (json == null) {
        return json;
    }
    return {
        
        'numPlayer': json['num_player'],
        'numMines': json['num_mines'],
        'x': json['x'],
        'y': json['y'],
    };
}

export function CreateGameToJSON(value?: CreateGame | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'num_player': value['numPlayer'],
        'num_mines': value['numMines'],
        'x': value['x'],
        'y': value['y'],
    };
}

