/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface DigSquare
 */
export interface DigSquare {
    /**
     * 0始まりのx座標
     * @type {number}
     * @memberof DigSquare
     */
    x: number;
    /**
     * 0始まりのy座標
     * @type {number}
     * @memberof DigSquare
     */
    y: number;
}

/**
 * Check if a given object implements the DigSquare interface.
 */
export function instanceOfDigSquare(value: object): boolean {
    if (!('x' in value)) return false;
    if (!('y' in value)) return false;
    return true;
}

export function DigSquareFromJSON(json: any): DigSquare {
    return DigSquareFromJSONTyped(json, false);
}

export function DigSquareFromJSONTyped(json: any, ignoreDiscriminator: boolean): DigSquare {
    if (json == null) {
        return json;
    }
    return {
        
        'x': json['x'],
        'y': json['y'],
    };
}

export function DigSquareToJSON(value?: DigSquare | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'x': value['x'],
        'y': value['y'],
    };
}

