/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
import type { GameStateEnum } from './GameStateEnum';
import {
    GameStateEnumFromJSON,
    GameStateEnumFromJSONTyped,
    GameStateEnumToJSON,
} from './GameStateEnum';

/**
 * 
 * @export
 * @interface FieldResult
 */
export interface FieldResult {
    /**
     * 
     * @type {Array<string>}
     * @memberof FieldResult
     */
    squares: Array<string>;
    /**
     * 
     * @type {GameStateEnum}
     * @memberof FieldResult
     */
    gameState: GameStateEnum;
    /**
     * 残り地雷数
     * @type {number}
     * @memberof FieldResult
     */
    minesLeft: number;
}

/**
 * Check if a given object implements the FieldResult interface.
 */
export function instanceOfFieldResult(value: object): boolean {
    if (!('squares' in value)) return false;
    if (!('gameState' in value)) return false;
    if (!('minesLeft' in value)) return false;
    return true;
}

export function FieldResultFromJSON(json: any): FieldResult {
    return FieldResultFromJSONTyped(json, false);
}

export function FieldResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldResult {
    if (json == null) {
        return json;
    }
    return {
        
        'squares': json['squares'],
        'gameState': GameStateEnumFromJSON(json['game_state']),
        'minesLeft': json['mines_left'],
    };
}

export function FieldResultToJSON(value?: FieldResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'squares': value['squares'],
        'game_state': GameStateEnumToJSON(value['gameState']),
        'mines_left': value['minesLeft'],
    };
}

