/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FieldResult
 */
export interface FieldResult {
    /**
     * 
     * @type {Array<string>}
     * @memberof FieldResult
     */
    squares: Array<string>;
}

/**
 * Check if a given object implements the FieldResult interface.
 */
export function instanceOfFieldResult(value: object): boolean {
    if (!('squares' in value)) return false;
    return true;
}

export function FieldResultFromJSON(json: any): FieldResult {
    return FieldResultFromJSONTyped(json, false);
}

export function FieldResultFromJSONTyped(json: any, ignoreDiscriminator: boolean): FieldResult {
    if (json == null) {
        return json;
    }
    return {
        
        'squares': json['squares'],
    };
}

export function FieldResultToJSON(value?: FieldResult | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'squares': value['squares'],
    };
}

