/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */

import { mapValues } from '../runtime';
/**
 * 
 * @export
 * @interface FlagSquare
 */
export interface FlagSquare {
    /**
     * 0始まりのx座標
     * @type {number}
     * @memberof FlagSquare
     */
    x: number;
    /**
     * 0始まりのy座標
     * @type {number}
     * @memberof FlagSquare
     */
    y: number;
}

/**
 * Check if a given object implements the FlagSquare interface.
 */
export function instanceOfFlagSquare(value: object): boolean {
    if (!('x' in value)) return false;
    if (!('y' in value)) return false;
    return true;
}

export function FlagSquareFromJSON(json: any): FlagSquare {
    return FlagSquareFromJSONTyped(json, false);
}

export function FlagSquareFromJSONTyped(json: any, ignoreDiscriminator: boolean): FlagSquare {
    if (json == null) {
        return json;
    }
    return {
        
        'x': json['x'],
        'y': json['y'],
    };
}

export function FlagSquareToJSON(value?: FlagSquare | null): any {
    if (value == null) {
        return value;
    }
    return {
        
        'x': value['x'],
        'y': value['y'],
    };
}

