/* tslint:disable */
/* eslint-disable */
/**
 * FastAPI
 * No description provided (generated by Openapi Generator https://github.com/openapitools/openapi-generator)
 *
 * The version of the OpenAPI document: 0.1.0
 * 
 *
 * NOTE: This class is auto generated by OpenAPI Generator (https://openapi-generator.tech).
 * https://openapi-generator.tech
 * Do not edit the class manually.
 */


/**
 * 
 * @export
 */
export const GameStateEnum = {
    GameOver: 'GAME_OVER',
    GameClear: 'GAME_CLEAR',
    Playing: 'PLAYING'
} as const;
export type GameStateEnum = typeof GameStateEnum[keyof typeof GameStateEnum];


export function GameStateEnumFromJSON(json: any): GameStateEnum {
    return GameStateEnumFromJSONTyped(json, false);
}

export function GameStateEnumFromJSONTyped(json: any, ignoreDiscriminator: boolean): GameStateEnum {
    return json as GameStateEnum;
}

export function GameStateEnumToJSON(value?: GameStateEnum | null): any {
    return value as any;
}

